parameters:
  test.one.command.class: App\TestOneBundle\Command\TestOneCommand

services:
  test.one.command:
    class: "%test.one.command.class%"
    public: true
    tags:
      - { name: command }
